### ISSUE TITLE
Line breaks in answers

### ISSUE THREAD

**Issue by TheCoward** [Retrospring/bugs#13]
Look, I know some people may use it to spam things, but it'd be nice to be able to put line breaks in answers. For example, you can make it so that you can't put two line breaks to each other, and there needs to be actual content behind.

**Comment by TheHowl** [comment]
Markdown already does that.

![](http://i.imgur.com/zMN27Ab.png)

rendered:

![](http://i.imgur.com/4KVu2lu.png)

Although, with the new maraku-dirty formatting ( Retrospring/retrospring#3 ) development of this might be required.

**Comment by TheCoward** [comment]
Oh, I guess I mistook the name of it. By line breaks, I mean this.
![linebreaks](https://a.pomf.se/bdrojn.png)

**Comment by pixeldesu** [comment]
This is because of markdown and already worked on with maruku-dirty!

**Comment by TheHowl** [comment]
got ninja'd by pixeldesu

**Comment by TheCoward** [comment]
Oh okay. I am a fucktard.
