### ISSUE TITLE
password resets don't work

### ISSUE THREAD

**Issue by agm0** [retrospring/bugs#18]
just kinda gives you a nice 404

**Comment by nilsding** [comment]
status update: that "reset your password" page works now, but sending the confirmation mail does not.  I'm onto the last part.

(commit `77b92b0b`)

**Comment by nilsding** [comment]
the mail is being sent now, changing the password still does not work.  ("reset password token is invalid")

(commit `149868c0`)

**Comment by nilsding** [comment]
resetting the password works now!

**Comment by alfateam123** [comment]
It works! thank you! （●´∀｀）ノ♡
