### ISSUE TITLE
Comment order is broken

### ISSUE THREAD

**Issue by pixeldesu** [Retrospring/bugs#23]
Well, self-explanatory. Sometimes it seems that comments are not ordered correctly to the time they were sent, causing confusing.

I haven't found an issue that is causing that yet, needs investigation

**Comment by TheHowl** [comment]
Can you give some example answers where this happens? I'd like to investigate.

**Comment by pixeldesu** [comment]
https://retrospring.net/pixeldesu/a/231752

my "Will please." should have appeared after the comment from Will, but it got placed on the top.

**Comment by TheHowl** [comment]
Oh yes, I've just seen this on a test thing. https://retrospring.net/Howl/a/237044

My best guess is that at the moment in the DB queries you aren't using the right one between `ASC` and `DESC`.

**Comment by yukimono** [comment]
Hah! It wasn't me!!
