### ISSUE TITLE
Profile headers

### ISSUE THREAD

**Issue by pixeldesu** [Retrospring/bugs#24]
_I'm opening an issue on something we were working on for quite a long time now, but this as a discussion for header size etc._

My header size in mind would be **1440x400px** as that scales quite good for all kinds of devices.

Here's is a current mockup I did with inspector tools directly onsite:
![screenshot-575](https://cloud.githubusercontent.com/assets/1774242/7281682/51977088-e92b-11e4-8dbd-8dcc72e891ef.png)

I'll do a redesign of the profile panel respectively to show the header and not hide it behind the profile picture.

**Comment by TheHowl** [comment]
Isn't this more or less the same as #5? :E

**Comment by pixeldesu** [comment]
Probably, it's more about profile headers than just customization thought, #5 is a bit vague.

**Comment by TheCoward** [comment]
What about making the block with the question asking thing slightly transparent and blurry?
