### ISSUE TITLE
Temporary bans

### ISSUE THREAD

**Issue by Filippus** [Retrospring/bugs#26]
Moderators and admins alike should be able to set a timer when a ban should expire. When a user logs in when temporary ban is active, the expiration date will be informed to them (also sent emails about the ban and the expiration date but that needs an automated email service).

**Comment by pixeldesu** [comment]
Something to add for bans, since this is already an issue related to banning: 

What about giving the admins the possibility to state a **ban reason** and a **time**. (or **no reason** and **permanent** banning)

**Comment by Filippus** [comment]
That too, but why no reason for permanent bans?

**Comment by pixeldesu** [comment]
that was just listing up, not limiting to just permanent bans.

**Comment by yukimono** [comment]
no reason *and* permanent banning.

not for :p

**Comment by TheCoward** [comment]
Shouldn't banned users be notified of the length (and lack thereof) and reason of their ban? By email or upon connecting, something.
