### ISSUE TITLE
Ability to Report Questions

### ISSUE THREAD

**Issue by thebluecorsair** [Retrospring/bugs#30]
At the current time, questions are not report-able which forces the user to report a profile, causing the moderation or administrative team to have to go through countless questions and attempt to find which one was worthy of being reported.

By adding the option to report or delete questions, this will allow for better support by the moderation team and allow for bad questions to be deleted more quickly.

**Comment by TheCoward** [comment]
This seems like a serious issue indeed.

**Comment by thebluecorsair** [comment]
This would also resolve issues around anonymous questions not being able to be moderated or removed in such cases of abuse, harrassive, or illegal questions.

**Comment by thebluecorsair** [comment]
This has since been implemented.
