### ISSUE TITLE
Frontpage x Particleground

### ISSUE THREAD

**Issue by pixeldesu** [Retrospring/bugs#34]
Something I'll mark off as idea, because I thought that would be kinda cool to add to the frontpage.

Particleground is dots moving around, getting connected by lines, Retrospring is connecting users with questions and answers. Also, Particleground looks cool.

I could write a gem for the Rails asset pipeline, if [I/someone else/whoever] will implement this later.

[Watch a demo of Particleground here](http://jnicol.github.io/particleground/)

**Comment by schisma** [comment]
:+1:

**Comment by TheCoward** [comment]
Yes please!

**Comment by pixeldesu** [comment]
Just added this!
