### ISSUE TITLE
The stats on the timeline page are a bit confusing

### ISSUE THREAD

**Issue by diamantlefou** [retrospring/bugs#36]
![2015-01-01_18-31-26](https://cloud.githubusercontent.com/assets/9307108/5592807/6f6a03c6-91e4-11e4-8333-ed149b968933.png)
When I look at the stats on the left of the timeline page, I'm never sure if "answers" means the number of questions I answered or the number of answers my questions got.
Same for the comments and smiles, are those the ones I posted or the ones I got?
How about putting one of those "bubbles" that pop when you put your cursor on top of the stat, explaining what the numbers mean more specifically.
Not exactly clear, sorry...

**Comment by pixeldesu** [comment]
These are all your stats, your count of followers/followings, questions, answers, comments and smiles.

I will look into improving this!

**Comment by squezey** [comment]
I also think the smiles should mean what people smiled at your answers, not what you have given out. I also think those stats should be on your profile page too, not just the timeline.

**Comment by pixeldesu** [comment]
I changed this now, so the stats on the timeline only show your follower/following count!
