### ISSUE TITLE
Break comments after words

### ISSUE THREAD

**Issue by KarimGeiger** [retrospring/bugs#37]
On mobile the comments break when the line ends no matter if the words end or not. It just destroys words which makes it damn hard to read.

**Comment by pixeldesu** [comment]
`break-word: break-all;`

I added  this in the beginning to (lazy) remove every possible way of people trying to break the site with commenting only one character.

Will fix this.

**Comment by pixeldesu** [comment]
fixed in commit `26f21f8e`
