### ISSUE TITLE
Page titles

### ISSUE THREAD

**Issue by pixeldesu** [Retrospring/bugs#37]
This has been missing for quite a long time now, since the `title` attribute is always the site title.

This could help users to know where they are, if the tab is not active, and help us seeing the pages visited over the analytics.

**Comment by yukimono** [comment]
I wonder if something like
```haml
- if @user
  %title 
    = @user.display_name
    | Retrospring
- elsif @answer
  %title 
    = @answer.user.display_name
    | Retrospring
- elsif @question
  %title 
    = @question.user.display_name
    | Retrospring
- else
  %title Retrospring
```
would work

**Comment by schisma** [comment]
@yukimono But what if some two of those exist at the same time? Can that happen?

**Comment by yukimono** [comment]
No.
