### ISSUE TITLE
real time inbox notification updates

### ISSUE THREAD

**Issue by squezey** [retrospring/bugs#38]
I noticed there's no real time notifications that appear in your inbox and the page needs to be refreshed to get any updates to it. If there's a way to I think it should be done in real time, it would be more helpful to people that leave the site open in another tab/window that wouldn't know that got anything until they decided to refresh the page and feel much more fluid overall to the experience.

**Comment by nilsding** [comment]
pretty much a dupe of #32.  it's a thing that's being worked on.
