### ISSUE TITLE
Header on page

### ISSUE THREAD

**Issue by aedotj** [retrospring/bugs#39]
## Some infos:
- Running Chrome in 1366x768
- Just signed up
- W10 Preview

I just signed up, and this is the page I got right then.
![prtscr capture_2](https://cloud.githubusercontent.com/assets/7189784/5601247/55c8aefc-92f4-11e4-84f9-1dd83d91c073.png)

Some F12ing showed me that changing ".container.j2-page" 's padding-top property from 30px to 80px made it perfect.
![prtscr capture_227](https://cloud.githubusercontent.com/assets/7189784/5601256/b6bc7950-92f4-11e4-858f-1ad55356c796.png)

**Comment by nilsding** [comment]
~~chrome confirmed for new IE6~~

what version are you using?  seems fine to me with 39.0.2171.71 (what the fuck are the version numbers even)

**Comment by aedotj** [comment]
I'm stupid.
I meant ~~Chrome~~ **Chromium**, [Torch Browser](http://torchbrowser.com/).
I don't think it should change anything though...
It runs on Chrome 36.0.1985.125.

**Comment by pixeldesu** [comment]
well, the navbar should in no means have 2 lines.

I don't know what the fuck is wrong here, I investigate this issue, because I already fixed this for all users that reported that issue, *until now*.

**Comment by pixeldesu** [comment]
**Side note:**  this seems to be an issue with WebKit.

**Comment by aedotj** [comment]
Well, fixed! Thanks!

**Comment by pixeldesu** [comment]
fixed with commit `16f319a0`
