### ISSUE TITLE
Discover

### ISSUE THREAD

**Issue by pixeldesu** [Retrospring/bugs#39]
This is something we had on mind for quite some time now, time to get some working drafts ready with your help.

The "Discover" page should contain information or lists about the last week/months most popular content/users so people find something they might be interested in, new people to follow and to interact with. This is a discussion thread to get input on what there should be on this page.

I'm proposing that it should be a **weekly roundup**, or just showing the stats of the last _7 days_.

* **Users**
  * ...most followed (on that week/last 7 days)
  * ...most sent questions
* **Questions**
  * ...with most answers
* **Answers**
  * ...with most smiles
  * ...with most comments

Post your ideas of what you imagine to be shown on the discover page.

**Notice:** Please don't suggest stuff that involves analyzing the users content yet to find perfect matches for new follow recommendations. Getting something like this done will probably take a bit, this is a step to get users to probably interesting content on the site!

**Comment by TheCoward** [comment]
A less general thing where there are for instance, answers of users that you don't follow but that have been smiled at by your followings.

**Comment by seatsea** [comment]
How about new users that have at least a few following so as to filter out empty accounts?

**Comment by schisma** [comment]
Offer a premium subscription to Retrospring so that users with one will be suggested on the Discover page.

**Comment by nilsding** [comment]
> Offer a premium subscription to Retrospring

Let's call that one Retrospring++, please!

**Comment by Moltenheim** [comment]
approval++;

**Comment by yukimono** [comment]
Wouldn't a lesser retrospring be Retrospring#?

**Comment by schisma** [comment]
>Wouldn't a lesser retrospring be Retrospring#?
I **almost** laughed.

**Comment by TheCoward** [comment]
I propose we call the lesser version "Retrospring" and the premium version 9GAG.

**Comment by Moltenheim** [comment]
How about the Spotify approach of calling the lesser version "Retrospring Free"?

**Comment by pixeldesu** [comment]
I propose that we keep on the subject ;__;

**Comment by nilsding** [comment]
The subject isn't "let's discuss what the Retrospring premium membership should be called"?  :cry:

**Comment by yukimono** [comment]
In all seriousness, twitter sends a "Discover Twitter" email once every few weeks or so that gives you like the four most responded to/retweeted/favourited tweets, so this is not entirely unconventional

**Comment by schisma** [comment]
That'd probably be a good idea. We certainly need to provide an option to regulate those mails though.

**Comment by yukimono** [comment]
implemented
