### ISSUE TITLE
Broken-Image-Sign instead of Default-Image

### ISSUE THREAD

**Issue by Stemw3** [retrospring/bugs#40]
When opening my Profile (or the Settings-tab) I don't get the Default-Wolf-like-Image, but the Broken-Image-notification.
Pics, cause every Report needs "Prove-pics" °^°:
Profile: http://puu.sh/e0WV9/2d50050096.png
And in the the Settings: http://puu.sh/e0X1J/9a7a5af05d.png

**Comment by pixeldesu** [comment]
Investigating, could you upload an image in the meantime?

**Comment by pixeldesu** [comment]
Somehow the files went missing on the server, this issue is fixed now!
