### ISSUE TITLE
Profile: Domain name is not displayed correctly

### ISSUE THREAD

**Issue by Dennis14e** [retrospring/bugs#43]
The display of the domain name stopped at a number:
![screenshot](https://cloud.githubusercontent.com/assets/5065163/5607320/aa10a9de-9456-11e4-94cb-09050cb2441e.PNG)

It should be: www.dennis14e.de
See it here: https://retrospring.net/@Dennis14e

**Comment by nilsding** [comment]
done 

(commit `3567ba61`)
