### ISSUE TITLE
Send with Cmd+Enter

### ISSUE THREAD

**Issue by uppfinnarn** [retrospring/bugs#45]
Being able to send stuff with Cmd+Enter/Ctrl+Enter is really nice, works on Github

**Comment by pixeldesu** [comment]
Ctrl+Enter works in the inbox, on question pages and for comments already.

**Comment by uppfinnarn** [comment]
Are you checking for Ctrl specifically? On OSX, you use Cmd+Enter, which sets the 'meta' flag on the event instead. I think I remember Ctrl doing that as well, so it might be worth just checking that flag instead of the ctrl one.

**Comment by ix** [comment]
this should be fixed now
