### ISSUE TITLE
Tooltips aren't fired on answers you load more

### ISSUE THREAD

**Issue by pixeldesu** [retrospring/bugs#47]
Absolutely low-priority javascript issue I just wanted to point out.

**Comment by yukimono** [comment]
if it's anything like my layering issue i had ages ago
i fixed it with adding a ``div`` to the root body element and hacky css 
```
.tooltip {
  position: absolute;
  top: 0; /* should override with JS pointer screenX */
  left: 0; /* should override with JS pointer screenY */
}
```

**Comment by pixeldesu** [comment]
It's no CSS issue, it just renders the browser-default tooltip (from the `title`attribute)

**Comment by yukimono** [comment]
What library are you using?

**Comment by pixeldesu** [comment]
We use the Tooltip scripts included within Bootstrap (so, jQuery + Bootstrap)

We initialize them the following way
``` coffeescript
($ document).ready -> ($ '[data-toggle="tooltip"]').tooltip()
```
and just need to call that again (except for the `document.ready` part, obviously) when we press a "Load more" button. The code for this is included, it's not working somehow, tho.

**Comment by yukimono** [comment]
![screen shot 2015-01-15 at 9 49 30 pm](https://cloud.githubusercontent.com/assets/614231/5761285/76c73216-9d00-11e4-864d-0751106ee344.png)

seems to be working fine for me, try selecting 
```javascript
$('[title]')
```

**Comment by yukimono** [comment]
it also worth noting that in the production version of the site at least, it has no elements with the title attribute so i can't really help much. (probably as intended)

**Comment by yukimono** [comment]
wait rather, now that i read the topic when i'm not tired and slightly drunk,

you have to reapply tooltips when loading more.
so every time you add new DOM elements with tooltips you have to query it up again, and apply tooltips all over.

so the solution to this is 
```javascript

for(;;) {
  $answer_div = $("<div>");
  //
  $answer_div.tooltip(); //<-------- this line
  $root.append($answer_div);
}
```

**Comment by nilsding** [comment]
­> using `for (;;) { … }` in non-Enterprise code
­> 2015

I'm sure there is a nicer way to that, such as attaching code to a event, or actually call that damn `$('[data-toggle="tooltip"]').tooltip()` in the button's callback function.

case closed

**Comment by yukimono** [comment]
well, js is entirely event based, ``document.ready`` is jut a wrapper around ``DOMContentLoaded``

``$(document).ready(function(){});`` translates into ``document.addEventListener("DOMContentLoaded", function(){});``

**Comment by yukimono** [comment]
well, that was the assumption with the ``for (;;)`` code, assuming the button's callback handler loops through the new answers and creates elements for them (in a loop).

also pseudocode because i don't know the entire code.
