### ISSUE TITLE
Implement AWS S3 for file uploads

### ISSUE THREAD

**Issue by pixeldesu** [Retrospring/bugs#48]
_"The space on our server is not infinite."_ explains this pretty much.

This would be something essential to have if we continue growing a lot of people will upload profile pictures, headers (@yukimono) and later on inline images into the site.

I'm pretty sure, since @nilsding already set this up on his account, could lend us the tokens we need for a proper AWS/S3 integration.

**Comment by yukimono** [comment]
[Paperclip is built around fog](https://github.com/thoughtbot/paperclip#defaults) so implementing it would only be adding or changing a few lines, but i don't know how we'll migrate the data.

**Comment by pixeldesu** [comment]
* **Option 1:** Some sort of migration script (over rake maybe?)
* **Option 2:** Purge and force people to reupload.

**Comment by yukimono** [comment]
probably option 1
https://gist.github.com/felixalias/924617

**Comment by TheHowl** [comment]
I'd personally go for the first one tbh

**Comment by yukimono** [comment]
yeah it looks like you just upload the ``system`` folder (``retrospring/public/system``) to the bucket root.

but i would test this first.

**Comment by yukimono** [comment]
that should do it, local files work but it's shifty.
