### ISSUE TITLE
Be more customisable  

### ISSUE THREAD

**Issue by XkNyronkX** [Retrospring/bugs#5]
be able to add more to you profile (I.E backgrounds, profile headers) or backgrounds that replace the standard white background when you look on the public timeline or followed time line

Makes you more able to make your own kind of retrospring 
or something
blah

**Comment by Moltenheim** [comment]
I'm pretty sure this is already being worked on.

**Comment by pixeldesu** [comment]
Yeah, it is! @yukimono added color theming as a pull request (retrospring/Retrospring#9) and we are currently checking the code for it!

**Comment by nilsding** [comment]
argh, I meant I closed #15!

**Comment by TheHowl** [comment]
yay!
