### ISSUE TITLE
Small Theme Request

### ISSUE THREAD

**Issue by thebluecorsair** [Retrospring/bugs#51]
Just a *small* theme request to add a few minimalistic designs to the current question/answer boxes, as well as the panels throughout the service. The actual opacity of the panel shadows can be darkened a bit however if they're not enough.

![image](https://cloud.githubusercontent.com/assets/1847891/7554397/a548c466-f6dc-11e4-8228-82c462c4a462.png)

**Add**
.panel { box-shadow: 0px 0px 20px rgba(0,0,0,0.1); }
.panel-default>.panel-heading { box-shadow: inset 0 -10px 10px -10px rgba(0,0,0,0.1); }

**Remove**
.panel-default { border-color: transparent; }

@pixeldesu pls.

**Comment by pixeldesu** [comment]
If you also take in consideration that the comment section might need shadows of this sort too, I'll add it :)

**Comment by thebluecorsair** [comment]
For the footer (comment section):
.panel-footer { box-shadow: inset 0 10px 10px -10px rgba(0,0,0,0.1); }
