### ISSUE TITLE
Ability to add users in groups

### ISSUE THREAD

**Issue by yungsenpai** [retrospring/bugs#51]
Being able to add users into different usergroups.
On timeline view, able to switch over so you can see the useractivity in the group.
When creating questions, being able to send to everyone/usergroups.
On userpage, being able to add/remove users to group, edit group and create new.

**Comment by nilsding** [comment]
Backend stuff is done… mostly.  It's all frontend work now.

**Comment by nilsding** [comment]
And it's live!  Go to an user's page, click on "Actions" and then "Manage group memberships".  You'll then be able to create a new group there.
