### ISSUE TITLE
ARRR, I WANT ME PARALLAX HEADARRRS

### ISSUE THREAD

**Issue by nilsding** [Retrospring/bugs#53]
the person whose implementation works and gets merged will be paid 2€ via PayPal™

**Comment by yukimono** [comment]
The person whose implementation works gets reverted and will owe me 985 RUB in damages via bank transfer.

**Comment by thebluecorsair** [comment]
The person who's implementation works and then is thus reverted by @yukimono owing 985 RUB in damages who then gets paid 2€ via PayPal™ by @nilsding will get 1.37$ USD via PayPal™ from myself in between one (1) and three hundred and sixty five (365) business days.

**Comment by yukimono** [comment]
i can't wait until someone takes this serious

**Comment by schisma** [comment]
Can I do it with JSSS?

**Comment by yukimono** [comment]
Only if it's [hieroglypically](http://patriciopalladino.com/blog/2012/08/09/non-alphanumeric-javascript.html) written.

**Comment by yukimono** [comment]
All above statements are invalid yooooo

**Comment by nilsding** [comment]
Re-opened because I still want them.

**Comment by nilsding** [comment]
Re-closed because I merged that PR.
