### ISSUE TITLE
Discover "New" Bubble.

### ISSUE THREAD

**Issue by thebluecorsair** [Retrospring/bugs#58]
Whenever the Discover page is updated with new information (which if I recall is either every day or weekly), possibly display a "new" bubble alerting users as such, also encouraging the use of the Discover page.

![image](https://cloud.githubusercontent.com/assets/1847891/7651206/adbc3aae-fab2-11e4-9407-92d2739baabb.png)

The above can be accomplished with 100% CSS. A little tinkering and love may be wanted to make it fit perfectly.

```css
.discover-new {
  position: relative;
  width: 50px;
  height: 30px;
  padding: 0px;
  background: rgba(0,0,0,0.3);
  -webkit-border-radius: 0px;
  -moz-border-radius: 0px;
  border-radius: 0px;
  color: #FFF;
  padding: 6px;
  margin-left: 15px;
  font-weight: bold;
}
.discover-new:after {
  content: '';
  position: absolute;
  border-style: solid;
  border-width: 10px 10px 10px 0;
  border-color: transparent rgba(0,0,0,0.3);
  display: block;
  width: 0;
  z-index: 1;
  left: -10px;
  top: 5px;
}```

**Comment by pixeldesu** [comment]
Discover consists of 4 SQL queries run every time a user visits the site to fetch the content, appending a `new` or `read` type to each of these basic user/answer/question objects would be pointless.

**Comment by thebluecorsair** [comment]
Was going to say possibly schedule an SQL query to be run once a day and then cache the result to save database requests, but if it can handle it, for the better to just run them each time. :stuck_out_tongue:
