### ISSUE TITLE
Deleting a group results in incorrect tooltip

### ISSUE THREAD

**Issue by easterncalculus** [retrospring/bugs#64]
![delete test 1](https://cloud.githubusercontent.com/assets/10490791/5789931/7f9e3546-9e78-11e4-8e5b-c5c530123bc7.png)
![delete test 2](https://cloud.githubusercontent.com/assets/10490791/5789934/9e113438-9e78-11e4-9fab-b5a20b3dc1c3.png)
Not sure if tooltip is the correct choice of words...
Also, if you create a group without specifying a name, it results in a generic error message, maybe add something for that. Great work on the update!

**Comment by nilsding** [comment]
Done, and done.
