### ISSUE TITLE
Old notification appearing above all others

### ISSUE THREAD

**Issue by NikoofDeath** [retrospring/bugs#69]
An old notification is appearing above every single other one. Refreshing does not help.
![4 hours ago](https://cloud.githubusercontent.com/assets/9629341/5868560/45da2f4a-a279-11e4-9e5e-099adebf1212.PNG)
![rsbug](https://cloud.githubusercontent.com/assets/9629341/5868583/813cc21e-a279-11e4-9757-4e444f50847b.PNG)
Even on a different browser, this issue persists.
![rsbug2](https://cloud.githubusercontent.com/assets/9629341/5868690/2d426d6a-a27b-11e4-896b-bd7c23950eba.PNG)

**Comment by nilsding** [comment]
This is because that notification's date is actually 4 hours in the future.
