### ISSUE TITLE
Question generator does not work if user disabled anonymous questions

### ISSUE THREAD

**Issue by pixeldesu** [retrospring/bugs#71]
...because the generated questions are *sent* from an anonymous user.

**Comment by TheHowl** [comment]
Maybe you could create an account called "Asker" or something and make him the one who asks stuff?

This would also be cool to see how many questions are asked by "The Asker"

**Comment by nilsding** [comment]
>Maybe you could create an account called "Asker" or something and make him the one who asks stuff?

Generated questions are stored internally with the user name "justask".

>This would also be cool to see how many questions are asked by "The Asker"

```
 count 
-------
  6027
(1 row)
```

**Comment by nilsding** [comment]
fixed.
