### ISSUE TITLE
Locales/Translations

### ISSUE THREAD

**Issue by pixeldesu** [Retrospring/bugs#71]
Just going to open this up again, since people requested it in the last bug tracker as well and this is current worked on either way. Also using this to keep track of what I finished localizing so far.

**Completed:**
- [x] About
- [x] Front
- [x] Discover
- [x] Inbox
- [x] Answerbox
  - [x] Comments
  - [x] Comment Smiles
  - [x] Smiles
- [x] Questionbox
- [x] Questions/Question Headers
- [x] Notifications
- [x] Actions _(Answer, Delete, Report, Return to Inbox...)_
- [x] User profiles
- [x] Moderation
- [x] Ajax calls
- [x] Flashes
- [x] Settings

**In Progress:**
- [ ] Javascript intern confirm dialogues and errors _(properly implement i18n-js)_

**Missing:**
- [ ] Check through all stuff again and replace missing stuff

**Comment by yukimono** [comment]
make sure you also translate the `flash[:notice]` popins.

**Comment by pixeldesu** [comment]
Already done!

**Comment by yukimono** [comment]
Assuming feature complete since merged with master.
