### ISSUE TITLE
Links to answers are broken

### ISSUE THREAD

**Issue by TheHowl** [Retrospring/bugs#77]
Homepage timeline, user profiles... all links to answer are broken. They either take back to the homepage if checking answers from the homepage, or if you're on an user's page, they take to `/user/<username>`. Also, the text inside the \<a\> seem to be using... Times new roman?

**Comment by TheHowl** [comment]
(also, just noticed - on [question pages](https://retrospring.net/Howl/q/144624) they take to the question page itself again)

**Comment by yukimono** [comment]
Weird, I can't reproduce this on local.

**Comment by TheHowl** [comment]
![works on my machine](https://cloud.githubusercontent.com/assets/4681308/8057634/5b4111cc-0eb3-11e5-8024-3d0c77520dc4.png)

**Comment by yukimono** [comment]
nope i found it

**Comment by yukimono** [comment]
pinging @pixeldesu / @nilsding to pull into retrospring.net.
