### ISSUE TITLE
"Ask a question" Tooltip Arrow Mis-positioned

### ISSUE THREAD

**Issue by thebluecorsair** [retrospring/bugs#81]
Currently, the tooltip that displays while hovering over the new question icon in the navigation bar is not aligned correctly with the tooltip itself and either overlaps or is hidden behind it.
![image](https://cloud.githubusercontent.com/assets/1847891/6186047/a3485f9c-b329-11e4-9745-f6ecd45e84f9.png)

**Comment by pixeldesu** [comment]
This is a weird issue, it's working properly on my end.

**Comment by nilsding** [comment]
What browser and OS are you using?  It works fine with Firefox 35 and Konqueror with both WebKit and KHTML engines on Unix.

**Comment by thebluecorsair** [comment]
I am using Google Chrome on OSX. Lastest version of both.

Tested the same issue just now in Firefox on OSX, and it was working as intended.

**Comment by TheHowl** [comment]
Using Chrome on Winbloze here, working fine.

**Comment by yukimono** [comment]
![screen shot 2015-02-17 at 2 51 28 am](https://cloud.githubusercontent.com/assets/614231/6219470/ee383b0c-b64f-11e4-8ee9-0025eb31ed97.png)
No clue if it got fixed or something, but i can't replicate the error on Chrome / OSX.

![screen shot 2015-02-17 at 2 52 25 am](https://cloud.githubusercontent.com/assets/614231/6219483/067e3c5c-b650-11e4-9968-519056a0074b.png)

probably zoomed out (press CMD+0) which does have the bug.
![screen shot 2015-02-17 at 2 53 21 am](https://cloud.githubusercontent.com/assets/614231/6219505/6676d3da-b650-11e4-987f-2d1771fcac28.png)

Kind of fixable by forcing ``zoom: reset`` on the ``.tooltip`` class but it messes with offsets.

**Comment by thebluecorsair** [comment]
Oh! Yes, I am on a Retina display, forgot this could effect certain graphics although would be a fault with Bootstrap, not Retrospring in that case. @pixeldesu @yukimono

**Comment by thebluecorsair** [comment]
As this is an issue with Retina display support with Bootstrap (likely) and thus unrelated to Retrospring, will close this issue. Thank you for the research @yukimono.
