### ISSUE TITLE
Should Nicholas Cage become the mascot of this site?

### ISSUE THREAD

**Issue by Filippus** [Retrospring/bugs#92]
Seriously discussion only pls.

**Comment by yukimono** [comment]
Pretty sure he's legally owned by Disney

**Comment by nilsding** [comment]
Isn't he already?

**Comment by Filippus** [comment]
We need to make a Kickstarter to buy Nicholas Cage. Calling it.

**Comment by wplanetary** [comment]
I think it's already been done.
